name: 'Secrets to env'
description: 'Generate env files from repository secrets'
inputs:
  secrets:
    description: 'json string of github repository secrets'
    required: true
  env:
    description: ''
    required: true
  prefix_dev:
    description: '__DEV__'
    required: false
  file_name_dev:
    description: '.env.dev'
    required: false
  prefix_prod:
    description: ''
    default: '__PROD__'
    required: false
  file_name_prod:
    description: ''
    default: '.env'
    required: false
  override_prod:
    description: ''
    required: false
    default: 'false'
runs:
  using: 'node14'
  main: 'index.js'
